In [1]:
import pandas as pd
from tensorflow.keras.models import load_model
import re
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [163]:
test=pd.read_excel('test-7.xlsx')

In [164]:
test

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       3     152     151     153     154     156     156     156     156   
1       8     146     147     149     149     150     150     150     151   
2       4     205     205     205     206     205     204     203     202   
3       3     152     151     153     154     156     156     156     156   
4      23     216     218     219     222     223     223     223     224   
5       3     152     151     153     154     156     156     156     156   
6      20     134     137     140     143     146     147     150     151   
7       4     205     205     205     206     205     204     203     202   
8      23     216     218     219     222     223     223     223     224   
9       0     185     187     189     192     193     194     195     198   
10      2      52      59      69      86      93      99     105     108   
11      2      52      59      69      86      93      99     105     108   
12      8     146     147     149     149     150     150     150     151   
13      3     152     151     153     154     156     156     156     156   
14      4     205     205     205     206     205     204     203     202   
15     13     164     169     171     173     175     177     180     181   
16     19     130     138     145     150     155     156     159     162   

    pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      155  ...       205       202       177       143       111        82   
1      151  ...       176       173       172       170       167       165   
2      202  ...       122       225       210       211       207       205   
3      155  ...       205       202       177       143       111        82   
4      226  ...       252       255       255       255       255       255   
5      155  ...       205       202       177       143       111        82   
6      152  ...       113       197       191       198       158        77   
7      202  ...       122       225       210       211       207       205   
8      226  ...       252       255       255       255       255       255   
9      197  ...        33        27        25        26        23        20   
10     110  ...       154       155       156       157       157       159   
11     110  ...       154       155       156       157       157       159   
12     151  ...       176       173       172       170       167       165   
13     155  ...       205       202       177       143       111        82   
14     202  ...       122       225       210       211       207       205   
15     181  ...        36       174       218       208       207       205   
16     165  ...       220       221       222       222       224       224   

    pixel781  pixel782  pixel783  pixel784  
0         58        52        42        38  
1        164       162       160       158  
2        203       202       199       198  
3         58        52        42        38  
4        255       255       255       255  
5         58        52        42        38  
6         67        61        52        50  
7        203       202       199       198  
8        255       255       255       255  
9         23        29        30        29  
10       158       160       160       162  
11       158       160       160       162  
12       164       162       160       158  
13        58        52        42        38  
14       203       202       199       198  
15       204       203       201       200  
16       224       225       225       225  

[17 rows x 785 columns]

In [165]:
del test['label']

In [166]:
test

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0      152     151     153     154     156     156     156     156     155   
1      146     147     149     149     150     150     150     151     151   
2      205     205     205     206     205     204     203     202     202   
3      152     151     153     154     156     156     156     156     155   
4      216     218     219     222     223     223     223     224     226   
5      152     151     153     154     156     156     156     156     155   
6      134     137     140     143     146     147     150     151     152   
7      205     205     205     206     205     204     203     202     202   
8      216     218     219     222     223     223     223     224     226   
9      185     187     189     192     193     194     195     198     197   
10      52      59      69      86      93      99     105     108     110   
11      52      59      69      86      93      99     105     108     110   
12     146     147     149     149     150     150     150     151     151   
13     152     151     153     154     156     156     156     156     155   
14     205     205     205     206     205     204     203     202     202   
15     164     169     171     173     175     177     180     181     181   
16     130     138     145     150     155     156     159     162     165   

    pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       156  ...       205       202       177       143       111        82   
1       150  ...       176       173       172       170       167       165   
2       200  ...       122       225       210       211       207       205   
3       156  ...       205       202       177       143       111        82   
4       227  ...       252       255       255       255       255       255   
5       156  ...       205       202       177       143       111        82   
6       153  ...       113       197       191       198       158        77   
7       200  ...       122       225       210       211       207       205   
8       227  ...       252       255       255       255       255       255   
9       196  ...        33        27        25        26        23        20   
10      113  ...       154       155       156       157       157       159   
11      113  ...       154       155       156       157       157       159   
12      150  ...       176       173       172       170       167       165   
13      156  ...       205       202       177       143       111        82   
14      200  ...       122       225       210       211       207       205   
15      182  ...        36       174       218       208       207       205   
16      168  ...       220       221       222       222       224       224   

    pixel781  pixel782  pixel783  pixel784  
0         58        52        42        38  
1        164       162       160       158  
2        203       202       199       198  
3         58        52        42        38  
4        255       255       255       255  
5         58        52        42        38  
6         67        61        52        50  
7        203       202       199       198  
8        255       255       255       255  
9         23        29        30        29  
10       158       160       160       162  
11       158       160       160       162  
12       164       162       160       158  
13        58        52        42        38  
14       203       202       199       198  
15       204       203       201       200  
16       224       225       225       225  

[17 rows x 784 columns]

In [167]:
test = test.values

In [168]:
test

array([[152, 151, 153, ...,  52,  42,  38],
       [146, 147, 149, ..., 162, 160, 158],
       [205, 205, 205, ..., 202, 199, 198],
       ...,
       [205, 205, 205, ..., 202, 199, 198],
       [164, 169, 171, ..., 203, 201, 200],
       [130, 138, 145, ..., 225, 225, 225]], dtype=int64)

In [169]:
test = test / 255

In [170]:
test = test.reshape(-1,28,28,1)

In [171]:
model = load_model('model.h5')

In [172]:
predictions = model.predict_classes(test)

In [173]:
print(predictions)

[ 3  8  4  3 22  3 19  4 22  0  2  2  8  3  4 12 18]


In [174]:
for i in range(len(predictions)):
    if(predictions[i] >= 9):
        predictions[i] += 1

In [175]:
print(predictions)

[ 3  8  4  3 23  3 20  4 23  0  2  2  8  3  4 13 19]


In [176]:
sentence = ''

In [177]:
for i in predictions:
    if i==0:
        sentence+='a'
    elif i==1:
        sentence+='b'
    elif i==2:
        sentence+='c'
    elif i==3:
        sentence+='d'
    elif i==4:
        sentence+='e'
    elif i==5:
        sentence+='f'
    elif i==6:
        sentence+='g'
    elif i==7:
        sentence+='h'
    elif i==8:
        sentence+='i'
    elif i==10:
        sentence+='k'
    elif i==11:
        sentence+='l'
    elif i==12:
        sentence+='m'
    elif i==13:
        sentence+='n'
    elif i==14:
        sentence+='o'
    elif i==15:
        sentence+='p'
    elif i==16:
        sentence+='q'
    elif i==17:
        sentence+='r'
    elif i==18:
        sentence+='s'
    elif i==19:
        sentence+='t'
    elif i==20:
        sentence+='u'  
    elif i==21:
        sentence+='v'
    elif i==22:
        sentence+='w'
    elif i==24:
        sentence+='y'
    else:
        sentence+=' '        

In [178]:
print(sentence)

died due accident


In [179]:
model2 = load_model('Disaster_Model.h5')

In [180]:

corpus1 = []
X1 = re.sub(r'https?:\/\/.*[\r\n]*', '', sentence)
X1 = re.sub(r'[^a-zA-Z]', ' ', X1)
X1= re.sub(r'#', '', X1)
corpus1.append(X1)
print(corpus1)

['died due accident']


In [181]:
voc_size = 50000
onehot_repr1 = [one_hot(words,voc_size) for words in list(corpus1)]
print(onehot_repr1)

[[43150, 45382, 14676]]


In [182]:
Length_of_tweet=20
embedded_docs1 = pad_sequences(np.array(onehot_repr1),padding='pre',maxlen=Length_of_tweet)
print(embedded_docs1)

[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0 43150 45382 14676]]


In [183]:
y_pred = model2.predict_classes(embedded_docs1)

In [184]:
print(y_pred)

[[0]]


In [185]:
for i in y_pred:
    for j in i:
        if j==1:
            print('The person is in happy space')
        else:
            print('The person is in a sad mood')

The person is in a sad mood
